### ISSUE TITLE
modules.F90(14): #error: #if: syntax error.

### ISSUE THREAD

**Issue by chrinide** [hokru/xopt#1]
Hi，

I use ifort 19 to compile the xopt, I got below error:

```
Makefile:112: extraneous text after 'ifeq' directive
Building: "2.0-dev"
writing new version.dat
ifort  -module mod -static -DINTEL -DDFTD3 -DGCP -DLBFGS -O2   -c src/modules.F90 -o build/modules.o  
modules.F90(14): #error: #if: syntax error.
modules.F90(14): #warning: illegal token on preprocessor directive line.
Makefile:181: recipe for target 'build/modules.o' failed
make: *** [build/modules.o] Error 1

```

Any suggestion?

**Comment by hokru** [comment]
Yes, it seems the new intel is picky about the syntax (rightfully so). You need to modify the offending line:

run this command (or edit yourself):
`sed -i s/"#elif GNU_LEGACY # 4.5"/"#elif GNU_LEGACY"/ src/modules.F90`

It is fixed in the `dev` branch. If you want to use it, note that you need to run with a selected Makefile `make -f configs/Makefile.intel.mkl`. There are some stability fixes included in the `dev` branch.
